# Generated by Django 2.0.5 on 2018-06-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20180626_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='Seminar', max_length=20),
            preserve_default=False,
        ),
    ]
