# Generated by Django 2.0.5 on 2018-06-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('SR', 'Seminar'), ('WS', 'Workshop')], default='SR', max_length=2),
        ),
    ]
