# Generated by Django 2.0.5 on 2018-06-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_auto_20180626_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='event_type',
        ),
    ]
