# Generated by Django 2.0.5 on 2018-07-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_url',
            field=models.URLField(blank=True),
        ),
    ]
