# Generated by Django 2.0.5 on 2018-10-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20181004_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
